spring:
  application:
    name: ems-algasensors-temperature-monitoring
  datasource:
    url: jdbc:h2:mem:algasensors-temperature-monitoring
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8082
